
------------------------------------------------------------------------------------
-- P.1 Muestre los 2 movimientos de proveedores mas grandes registrados en el kardex
-- en los últimos 90 días       1.5
------------------------------------------------------------------------------------
SELECT *
FROM (SELECT P.CODPROVEEDOR,P.NOMPROVEEDOR,K.CODMOVIMIENTO,K.FECHA,K.CANTIDAD
        FROM EX1_KARDEX K, EX1_PROVEEDOR P
        WHERE K.CODPROVEEDOR = P.CODPROVEEDOR
        AND  TIPOPERACION LIKE 'I%'
        AND FECHA BETWEEN SYSDATE-90 AND SYSDATE
        ORDER BY CANTIDAD DESC)
WHERE   ROWNUM <=2;      

------------------------------------------------------------------------
-- P.2 MUESTRE LAS OPERACIONES DEL KARDEX Y SU RESPECTIVO PROVEEDOR   1.0
------------------------------------------------------------------------

SELECT P.CODPROVEEDOR,P.NOMPROVEEDOR,CODMOVIMIENTO,-1*K.CANTIDAD CANTIDAD
FROM EX1_KARDEX K, EX1_PROVEEDOR P
WHERE K.CODPROVEEDOR = P.CODPROVEEDOR
AND  TIPOPERACION LIKE 'S%'
UNION ALL
SELECT P.CODPROVEEDOR,P.NOMPROVEEDOR,CODMOVIMIENTO,K.CANTIDAD CANTIDAD
FROM EX1_KARDEX K, EX1_PROVEEDOR P
WHERE K.CODPROVEEDOR = P.CODPROVEEDOR
AND  TIPOPERACION LIKE 'I%';


-------------------------------------------------------------------------------------
--- P.3 Muestre las recetas activas donde alguno de sus componentes ha sido vendido por 
-- un proveedor, el reporte debe mostrar el proveedor y componente, además de la receta y version
------------------------------------------------------------------------------------
--   2.0
SELECT  P.CODPROVEEDOR,P.NOMPROVEEDOR,R.CODPRODUCTO,R.VERSION,D.CODPRODUCTO COMPONENTE
        ,D.NOMPRODUCTO
        FROM EX1_KARDEX K, EX1_PROVEEDOR P, EX1_RECETA R, EX1_DETALLE_RECETA DR,
            EX1_PRODUCTO D
        WHERE K.CODPROVEEDOR = P.CODPROVEEDOR
        AND  K.TIPOPERACION LIKE 'I%'
        AND DR.CODCOMPONENTE = K.CODPRODUCTO
        AND R.VERSION = DR.VERSION
        AND R.CODPRODUCTO = DR.CODPRODUCTO
        AND R.ESTADO ='A'
        AND D.CODPRODUCTO = K.CODPRODUCTO
GROUP BY P.CODPROVEEDOR,P.NOMPROVEEDOR,R.CODPRODUCTO,R.VERSION,D.CODPRODUCTO,D.NOMPRODUCTO        
ORDER BY D.CODPRODUCTO




----------------------------------------------------------------------------------------



SELECT A.CODALMACEN, K.CODPRODUCTO,P.UNIDAD,MAX(CANTIDAD) 
FROM EX1_ALMACEN A,EX1_STOCK K,EX1_PRODUCTO P
WHERE A.CODALMACEN = K.CODALMACEN
AND P.CODPRODUCTO = K.CODPRODUCTO
GROUP BY  A.CODALMACEN, K.CODPRODUCTO,P.UNIDAD
ORDER BY A.CODALMACEN, K.CODPRODUCTO,P.UNIDAD;


SELECT A.CODALMACEN,P.UNIDAD,MAX(CANTIDAD) 
FROM EX1_ALMACEN A,EX1_STOCK K,EX1_PRODUCTO P
WHERE A.CODALMACEN = K.CODALMACEN
AND P.CODPRODUCTO = K.CODPRODUCTO
GROUP BY  A.CODALMACEN,P.UNIDAD
ORDER BY A.CODALMACEN, P.UNIDAD;

-- P.4 MUESTRE LOS PRODUCTOS SEGÚN LA UNIDAD DE MEDIDA QUE TIENEN MAYOR STOCK EN 
-- CADA ALMACEN, EL REPORTE DEBE MOSTRAR EL ALMACEN, CODIGO Y NOMBRE DEL PRODUCTO
-- la unidad y la cantidad.
-- 2.5
SELECT S.CODALMACEN,P.CODPRODUCTO,P.NOMPRODUCTO, P.UNIDAD,MAXIMO
FROM EX1_PRODUCTO P, EX1_STOCK S,
                    (SELECT A.CODALMACEN,P.UNIDAD,MAX(CANTIDAD) MAXIMO
                    FROM EX1_ALMACEN A,EX1_STOCK K,EX1_PRODUCTO P
                    WHERE A.CODALMACEN = K.CODALMACEN
                    AND P.CODPRODUCTO = K.CODPRODUCTO
                    GROUP BY  A.CODALMACEN,P.UNIDAD
                    ORDER BY A.CODALMACEN, P.UNIDAD) M
WHERE S.CODALMACEN = M.CODALMACEN
AND S.CODPRODUCTO = P.CODPRODUCTO
AND S.CANTIDAD = M.MAXIMO;

----------------------------------------------------------------------------------
-- P.5 Muestre todos los productos intermedios que tiene el sistema, y sus respectivas
-- componentes de su receta    2.5

SELECT P.NOMPRODUCTO,C.NOMPRODUCTO COMPONENTE,CANTIDAD,C.UNIDAD
FROM EX1_DETALLE_RECETA DR, EX1_PRODUCTO P,EX1_PRODUCTO C,EX1_RECETA R
WHERE DR.CODPRODUCTO = P.CODPRODUCTO
AND DR.CODCOMPONENTE = C.CODPRODUCTO
AND R.CODPRODUCTO = DR.CODPRODUCTO
AND DR.VERSION = R.VERSION
AND R.ESTADO = 'A'
AND DR.CODPRODUCTO  IN ( SELECT CODCOMPONENTE 
                                FROM EX1_DETALLE_RECETA)
ORDER BY P.NOMPRODUCTO,C.NOMPRODUCTO;
                                  

-----------------------------------------------------------------------------------
-- P.6 Por error se han guardado algunos productos en los almacenes de productos intermedios
-- (2XXX) por tal motivo debe desarrollar un reporte que muestre que productos no deben considerarse
-- 3.0

CREATE VIEW V_INTERMEDIOS
AS
        SELECT P.CODPRODUCTO,C.CODPRODUCTO AS COMPONENTE,CANTIDAD,C.UNIDAD
        FROM EX1_DETALLE_RECETA DR, EX1_PRODUCTO P,EX1_PRODUCTO C,EX1_RECETA R
        WHERE DR.CODPRODUCTO = P.CODPRODUCTO
        AND DR.CODCOMPONENTE = C.CODPRODUCTO
        AND R.CODPRODUCTO = DR.CODPRODUCTO
        AND DR.VERSION = R.VERSION
        AND R.ESTADO = 'A'
        AND DR.CODPRODUCTO  IN ( SELECT CODCOMPONENTE 
                                        FROM EX1_DETALLE_RECETA)
                                  
SELECT * FROM V_INTERMEDIOS

SELECT P.CODPRODUCTO, P.NOMPRODUCTO,CANTIDAD
FROM EX1_STOCK S,EX1_PRODUCTO P
WHERE S.CODALMACEN LIKE '2%'
AND S.CODPRODUCTO NOT  IN (SELECT CODPRODUCTO FROM V_INTERMEDIOS)
AND  S.CODPRODUCTO = P.CODPRODUCTO


--------------------------------------------------------------------------------------------    
-- P.7   OBTENGA UN REPORTE DE SALDO DE PRODUCTOS
-- DE LAS OPERACIONES DEL MES DE MARZO DEL 2020    2.5
-- 
SELECT ADD_MONTHS(SYSDATE+10,-3)
FROM DUAL;

CREATE VIEW V_MOVIMIENTOS
AS
SELECT CODPRODUCTO,SUM(CANTIDAD) CANTIDAD
FROM EX1_KARDEX K
WHERE TO_CHAR(FECHA,'MM/YYYY') = TO_CHAR(ADD_MONTHS(SYSDATE,-3),'MM/YYYY')
AND K.TIPOPERACION LIKE 'I%'
GROUP BY CODPRODUCTO
UNION ALL
SELECT CODPRODUCTO,-1*SUM(CANTIDAD) CANTIDAD
FROM EX1_KARDEX K
WHERE TO_CHAR(FECHA,'MM/YYYY') = TO_CHAR(ADD_MONTHS(SYSDATE,-3),'MM/YYYY')
AND K.TIPOPERACION LIKE 'S%'
GROUP BY CODPRODUCTO

SELECT P.CODPRODUCTO,P.NOMPRODUCTO,SUM(V.CANTIDAD) SALDO
FROM PRODUCTO P, V_MOVIMIENTOS V
WHERE P.CODPRODUCTO = V.CODPRODUCTO
GROUP BY P.CODPRODUCTO,P.NOMPRODUCTO
HAVING SUM(V.CANTIDAD)>0
ORDER BY CODPRODUCTO;


---------------------------------------------------------------------------------------------
---P.8 Cargue el stock del almacen de productos intermedios al almacen
---materia prima (1001)    1.0

-- INSERT E UPDATE SEGÚN EL PRODUCTO    

