CREATE TABLE SA_AGENCIA
  (
    ID_AGENCIA           NUMBER NOT NULL ,
    NOMBRE               VARCHAR2 (50 BYTE) NOT NULL ,
    ESTADO               NUMBER NOT NULL ,
    USUARIO_CREACION     VARCHAR2 (30 BYTE) NOT NULL ,
    FECHA_CREACION       DATE NOT NULL ,
    USUARIO_MODIFICACION VARCHAR2 (30 BYTE) ,
    FECHA_MODIFICACION   DATE
  ) ;
COMMENT ON COLUMN SA_AGENCIA.ID_AGENCIA
IS
  'IDENTIFICADOR DE LA AGENCIA' ;
  COMMENT ON COLUMN SA_AGENCIA.NOMBRE
IS
  'NOMBRE DE LA AGENCIA' ;
  COMMENT ON COLUMN SA_AGENCIA.ESTADO
IS
  '0: INACTIVO, 1: ACTIVO' ;
  COMMENT ON COLUMN SA_AGENCIA.USUARIO_CREACION
IS
  'USUARIO CREACION' ;
  COMMENT ON COLUMN SA_AGENCIA.FECHA_CREACION
IS
  'FECHA CREACION' ;
  COMMENT ON COLUMN SA_AGENCIA.USUARIO_MODIFICACION
IS
  'USUARIO MODIFICACION' ;
  COMMENT ON COLUMN SA_AGENCIA.FECHA_MODIFICACION
IS
  'FECHA MODIFICACION' ;
ALTER TABLE SA_AGENCIA ADD CONSTRAINT SA_AGENCIA_PK PRIMARY KEY ( ID_AGENCIA ) ;


CREATE TABLE SA_ALERTA
  (
    ID_ALERTA            NUMBER NOT NULL ,
    NOMBRE               VARCHAR2 (50 BYTE) NOT NULL ,
    ESTADO               NUMBER NOT NULL ,
    USUARIO_CREACION     VARCHAR2 (30 BYTE) NOT NULL ,
    FECHA_CREACION       DATE NOT NULL ,
    USUARIO_MODIFICACION VARCHAR2 (30 BYTE) ,
    FECHA_MODIFICACION   DATE
  ) ;
COMMENT ON COLUMN SA_ALERTA.ID_ALERTA
IS
  'IDENTIFICADOR DE LA ALERTA' ;
  COMMENT ON COLUMN SA_ALERTA.NOMBRE
IS
  'NOMBRE DE LA ALERTA' ;
  COMMENT ON COLUMN SA_ALERTA.ESTADO
IS
  '0: INACTIVO, 1: ACTIVO' ;
  COMMENT ON COLUMN SA_ALERTA.USUARIO_CREACION
IS
  'USUARIO CREACION' ;
  COMMENT ON COLUMN SA_ALERTA.FECHA_CREACION
IS
  'FECHA CREACION' ;
  COMMENT ON COLUMN SA_ALERTA.USUARIO_MODIFICACION
IS
  'USUARIO MODIFICACION' ;
  COMMENT ON COLUMN SA_ALERTA.FECHA_MODIFICACION
IS
  'FECHA MODIFICACION' ;
ALTER TABLE SA_ALERTA ADD CONSTRAINT SA_ALERTA_PK PRIMARY KEY ( ID_ALERTA ) ;


CREATE TABLE SA_CLIENTE
  (
    ID_CLIENTE           NUMBER NOT NULL ,
    ID_TIPO_CLIENTE      NUMBER NOT NULL ,
    NOMBRES              VARCHAR2 (50 BYTE) ,
    APELLIDO_PATERNO     VARCHAR2 (50 BYTE) ,
    APELLIDO_MATERNO     VARCHAR2 (50 BYTE) ,
    DOI                  VARCHAR2 (15 BYTE) ,
    RAZON_SOCIAL         VARCHAR2 (100 BYTE) ,
    NOMBRE_COMERCIAL     VARCHAR2 (100 BYTE) ,
    TELEFONO             VARCHAR2 (30 BYTE) ,
    CORREO_ELECTRONICO   VARCHAR2 (100 BYTE) NOT NULL ,
    ESTADO               NUMBER  ,
    USUARIO_CREACION     VARCHAR2 (30 BYTE)  ,
    FECHA_CREACION       DATE  ,
    USUARIO_MODIFICACION VARCHAR2 (30 BYTE) ,
    FECHA_MODIFICACION   DATE
  ) ;
COMMENT ON COLUMN SA_CLIENTE.ID_CLIENTE
IS
  'IDENTIFICADOR DEL CLIENTE' ;
  COMMENT ON COLUMN SA_CLIENTE.ID_TIPO_CLIENTE
IS
  'IDENTIFICADOR DEL TIPO DE CLIENTE' ;
  COMMENT ON COLUMN SA_CLIENTE.NOMBRES
IS
  'NOMBRE DEL CLIENTE' ;
  COMMENT ON COLUMN SA_CLIENTE.APELLIDO_PATERNO
IS
  'APELLIDO PATERNO DEL CLIENTE' ;
  COMMENT ON COLUMN SA_CLIENTE.APELLIDO_MATERNO
IS
  'APELLIDO MATERNO DEL CLIENTE' ;
  COMMENT ON COLUMN SA_CLIENTE.DOI
IS
  'DOCUMENTO OFICIAL DE IDENTIDAD' ;
  COMMENT ON COLUMN SA_CLIENTE.RAZON_SOCIAL
IS
  'RAZON SOCIAL DEL CLIENTE' ;
  COMMENT ON COLUMN SA_CLIENTE.NOMBRE_COMERCIAL
IS
  'NOMBRE COMERCIAL DEL CLIENTE' ;
  COMMENT ON COLUMN SA_CLIENTE.TELEFONO
IS
  'TELEFONO DEL CLIENTE' ;
  COMMENT ON COLUMN SA_CLIENTE.CORREO_ELECTRONICO
IS
  'CORREO ELECTRONICO DEL CLIENTE' ;
  COMMENT ON COLUMN SA_CLIENTE.ESTADO
IS
  '0: INACTIVO, 1: ACTIVO' ;
  COMMENT ON COLUMN SA_CLIENTE.USUARIO_CREACION
IS
  'USUARIO CREACION' ;
  COMMENT ON COLUMN SA_CLIENTE.FECHA_CREACION
IS
  'FECHA CREACION' ;
  COMMENT ON COLUMN SA_CLIENTE.USUARIO_MODIFICACION
IS
  'USUARIO MODIFICACION' ;
  COMMENT ON COLUMN SA_CLIENTE.FECHA_MODIFICACION
IS
  'FECHA MODIFICACION' ;
ALTER TABLE SA_CLIENTE ADD CONSTRAINT SA_CLIENTE_PK PRIMARY KEY ( ID_CLIENTE ) ;


CREATE TABLE SA_DEPARTAMENTO
  (
    ID_DEPARTAMENTO CHAR (6 BYTE) NOT NULL ,
    NOMBRE          VARCHAR2 (50 BYTE) NOT NULL
  ) ;
COMMENT ON COLUMN SA_DEPARTAMENTO.ID_DEPARTAMENTO
IS
  'IDENTIFICADOR DEL DEPARTAMENTO' ;
  COMMENT ON COLUMN SA_DEPARTAMENTO.NOMBRE
IS
  'NOMBRE DEL DEPARTAMENTO' ;
ALTER TABLE SA_DEPARTAMENTO ADD CONSTRAINT SA_DEPARTAMENTO_PK PRIMARY KEY ( ID_DEPARTAMENTO ) ;


CREATE TABLE SA_DETALLE_ALERTA
  (
    ID_DETALLE_ALERTA    NUMBER NOT NULL ,
    ID_ALERTA            NUMBER NOT NULL ,
    ID_OPERACION         NUMBER NOT NULL ,
    FECHA_REGISTRO       DATE NOT NULL ,
    ESTADO               NUMBER NOT NULL ,
    USUARIO_CREACION     VARCHAR2 (30 BYTE) NOT NULL ,
    FECHA_CREACION       DATE NOT NULL ,
    USUARIO_MODIFICACION VARCHAR2 (30 BYTE) ,
    FECHA_MODIFICACION   DATE
  ) ;
COMMENT ON COLUMN SA_DETALLE_ALERTA.ID_DETALLE_ALERTA
IS
  'IDENTIFICADOR DEL DETALLE DE LA ALERTA' ;
  COMMENT ON COLUMN SA_DETALLE_ALERTA.ID_ALERTA
IS
  'IDENTIFICADOR DE LA ALERTA' ;
  COMMENT ON COLUMN SA_DETALLE_ALERTA.ID_OPERACION
IS
  'IDNETIFICADOR DE LA OPERACION' ;
  COMMENT ON COLUMN SA_DETALLE_ALERTA.FECHA_REGISTRO
IS
  'FECHA DE REGISTRO' ;
  COMMENT ON COLUMN SA_DETALLE_ALERTA.ESTADO
IS
  '0: INACTIVO, 1: ACTIVO' ;
  COMMENT ON COLUMN SA_DETALLE_ALERTA.USUARIO_CREACION
IS
  'USUARIO CREACION' ;
  COMMENT ON COLUMN SA_DETALLE_ALERTA.FECHA_CREACION
IS
  'FECHA CREACION' ;
  COMMENT ON COLUMN SA_DETALLE_ALERTA.USUARIO_MODIFICACION
IS
  'USUARIO MODIFICACION' ;
  COMMENT ON COLUMN SA_DETALLE_ALERTA.FECHA_MODIFICACION
IS
  'FECHA MODIFICACION' ;
ALTER TABLE SA_DETALLE_ALERTA ADD CONSTRAINT SA_DETALLE_ALERTA_PK PRIMARY KEY ( ID_DETALLE_ALERTA ) ;


CREATE TABLE SA_DIRECCION
  (
    ID_DIRECCION         NUMBER NOT NULL ,
    DIRECCION            VARCHAR2 (150 BYTE) NOT NULL ,
    ESTADO               NUMBER NOT NULL ,
    ID_CLIENTE           NUMBER NOT NULL ,
    ID_DISTRITO          CHAR (6 BYTE) NOT NULL ,
    USUARIO_CREACION     VARCHAR2 (30 BYTE) ,
    FECHA_CREACION       DATE ,
    USUARIO_MODIFICACION VARCHAR2 (30 BYTE) ,
    FECHA_MODIFICACION   DATE
  ) ;
COMMENT ON COLUMN SA_DIRECCION.ID_DIRECCION
IS
  'IDENTIFICADOR DE LA DIRECCION' ;
  COMMENT ON COLUMN SA_DIRECCION.DIRECCION
IS
  'DESCRIPCION DE LA DIRECCION' ;
  COMMENT ON COLUMN SA_DIRECCION.ESTADO
IS
  '0: INACTIVO, 1: ACTIVO' ;
  COMMENT ON COLUMN SA_DIRECCION.ID_CLIENTE
IS
  'IDENTIFICADOR DEL CLIENTE' ;
  COMMENT ON COLUMN SA_DIRECCION.ID_DISTRITO
IS
  'IDENTIFICADOR DEL DISTRITO' ;
  COMMENT ON COLUMN SA_DIRECCION.USUARIO_CREACION
IS
  'USUARIO CREACION' ;
  COMMENT ON COLUMN SA_DIRECCION.FECHA_CREACION
IS
  'FECHA CREACION' ;
  COMMENT ON COLUMN SA_DIRECCION.USUARIO_MODIFICACION
IS
  'USUARIO MODIFICACION' ;
  COMMENT ON COLUMN SA_DIRECCION.FECHA_MODIFICACION
IS
  'FECHA MODIFICACION' ;
ALTER TABLE SA_DIRECCION ADD CONSTRAINT SA_DIRECCION_PK PRIMARY KEY ( ID_DIRECCION ) ;


CREATE TABLE SA_DISTRITO
  (
    ID_DISTRITO  CHAR (6 BYTE) NOT NULL ,
    NOMBRE       VARCHAR2 (50 BYTE) NOT NULL ,
    ID_PROVINCIA CHAR (6 BYTE) NOT NULL
  ) ;
COMMENT ON COLUMN SA_DISTRITO.ID_DISTRITO
IS
  'IDENTIFICADOR DEL DISTRITO' ;
  COMMENT ON COLUMN SA_DISTRITO.NOMBRE
IS
  'NOMBRE DEL DISTRITO' ;
  COMMENT ON COLUMN SA_DISTRITO.ID_PROVINCIA
IS
  'IDENTIFICADOR DE LA PROVINCIA' ;
ALTER TABLE SA_DISTRITO ADD CONSTRAINT SA_DISTRITO_PK PRIMARY KEY ( ID_DISTRITO ) ;


CREATE TABLE SA_OPERACION
  (
    ID_OPERACION              NUMBER NOT NULL ,
    CODIGO_OPERACION          VARCHAR2 (10 BYTE) NOT NULL ,
    ID_CLIENTE_REMITENTE      NUMBER NOT NULL ,
    ID_CLIENTE_DESTINATARIO   NUMBER NOT NULL ,
    ID_DIRECCION_REMITENTE    NUMBER ,
    ID_DIRECCION_DESTINATARIO NUMBER ,
    MONTO_OPERACION           NUMBER (10,2) NOT NULL ,
    ID_AGENCIA                NUMBER  ,
    FECHA_OPERACION           DATE  ,
    ESTADO                    NUMBER  ,
    USUARIO_CREACION          VARCHAR2 (30 BYTE)  ,
    FECHA_CREACION            DATE  ,
    USUARIO_MODIFICACION      VARCHAR2 (30 BYTE) ,
    FECHA_MODIFICACION        DATE
  ) ;
COMMENT ON COLUMN SA_OPERACION.ID_OPERACION
IS
  'IDENTIFICADOR DE LA OPERACION' ;
  COMMENT ON COLUMN SA_OPERACION.CODIGO_OPERACION
IS
  'CODIGO DE LA OPERACION' ;
  COMMENT ON COLUMN SA_OPERACION.ID_CLIENTE_REMITENTE
IS
  'IDENTIFICADOR DEL CLIENTE REMITENTE' ;
  COMMENT ON COLUMN SA_OPERACION.ID_CLIENTE_DESTINATARIO
IS
  'IDENTIFICADOR DEL CLIENTE DESTINATARIO' ;
  COMMENT ON COLUMN SA_OPERACION.ID_DIRECCION_REMITENTE
IS
  'IDENTIFICADOR DE LA DIRECCION DEL REMITENTE' ;
  COMMENT ON COLUMN SA_OPERACION.ID_DIRECCION_DESTINATARIO
IS
  'IDENTIFICADOR DE LA DIRECCION DEL DESTINATARIO' ;
  COMMENT ON COLUMN SA_OPERACION.MONTO_OPERACION
IS
  'MONTO DE LA OPERACION EN SOLES' ;
  COMMENT ON COLUMN SA_OPERACION.ID_AGENCIA
IS
  'IDENTIFICADOR DE LA AGENCIA' ;
  COMMENT ON COLUMN SA_OPERACION.FECHA_OPERACION
IS
  'FECHA DE LA OPERACION' ;
  COMMENT ON COLUMN SA_OPERACION.ESTADO
IS
  '0: INACTIVO, 1: ACTIVO' ;
  COMMENT ON COLUMN SA_OPERACION.USUARIO_CREACION
IS
  'USUARIO CREACION' ;
  COMMENT ON COLUMN SA_OPERACION.FECHA_CREACION
IS
  'FECHA CREACION' ;
  COMMENT ON COLUMN SA_OPERACION.USUARIO_MODIFICACION
IS
  'USUARIO MODIFICACION' ;
  COMMENT ON COLUMN SA_OPERACION.FECHA_MODIFICACION
IS
  'FECHA MODIFICACION' ;
ALTER TABLE SA_OPERACION ADD CONSTRAINT SA_OPERACION_PK PRIMARY KEY ( ID_OPERACION ) ;


CREATE TABLE SA_PROVINCIA
  (
    ID_PROVINCIA    CHAR (6 BYTE) NOT NULL ,
    NOMBRE          VARCHAR2 (50 BYTE) NOT NULL ,
    ID_DEPARTAMENTO CHAR (6 BYTE) NOT NULL
  ) ;
COMMENT ON COLUMN SA_PROVINCIA.ID_PROVINCIA
IS
  'IDENTIFICADOR DE LA PROVINCIA' ;
  COMMENT ON COLUMN SA_PROVINCIA.NOMBRE
IS
  'NOMBRE DE LA PROVINCIA' ;
  COMMENT ON COLUMN SA_PROVINCIA.ID_DEPARTAMENTO
IS
  'IDENTIFICADOR DEL DEPARTAMENTO' ;
ALTER TABLE SA_PROVINCIA ADD CONSTRAINT SA_PROVINCIA_PK PRIMARY KEY ( ID_PROVINCIA ) ;


CREATE TABLE SA_TIPO_CLIENTE
  (
    ID_TIPO_CLIENTE      NUMBER NOT NULL ,
    NOMBRE               VARCHAR2 (20 BYTE) NOT NULL ,
    ESTADO               NUMBER NOT NULL ,
    USUARIO_CREACION     VARCHAR2 (30 BYTE)  ,
    FECHA_CREACION       DATE  ,
    USUARIO_MODIFICACION VARCHAR2 (30 BYTE) ,
    FECHA_MODIFICACION   DATE
  ) ;
COMMENT ON COLUMN SA_TIPO_CLIENTE.ID_TIPO_CLIENTE
IS
  'IDENTIFICADOR DEL TIPO DE CLIENTE' ;
  COMMENT ON COLUMN SA_TIPO_CLIENTE.NOMBRE
IS
  'NOMBRE DEL TIPO DE CLIENTE' ;
  COMMENT ON COLUMN SA_TIPO_CLIENTE.ESTADO
IS
  '0: INACTIVO, 1: ACTIVO' ;
  COMMENT ON COLUMN SA_TIPO_CLIENTE.USUARIO_CREACION
IS
  'USUARIO CREACION' ;
  COMMENT ON COLUMN SA_TIPO_CLIENTE.FECHA_CREACION
IS
  'FECHA CREACION' ;
  COMMENT ON COLUMN SA_TIPO_CLIENTE.USUARIO_MODIFICACION
IS
  'USUARIO MODIFICACION' ;
  COMMENT ON COLUMN SA_TIPO_CLIENTE.FECHA_MODIFICACION
IS
  'FECHA MODIFICACION' ;
ALTER TABLE SA_TIPO_CLIENTE ADD CONSTRAINT SA_TIPO_CLIENTE_PK PRIMARY KEY ( ID_TIPO_CLIENTE ) ;


ALTER TABLE SA_OPERACION ADD CONSTRAINT SA_AGENCIA_FK FOREIGN KEY ( ID_AGENCIA ) REFERENCES SA_AGENCIA ( ID_AGENCIA ) ;

ALTER TABLE SA_DETALLE_ALERTA ADD CONSTRAINT SA_ALERTA_FK FOREIGN KEY ( ID_ALERTA ) REFERENCES SA_ALERTA ( ID_ALERTA ) ;

ALTER TABLE SA_OPERACION ADD CONSTRAINT SA_CLIENTE_DES_FK FOREIGN KEY ( ID_CLIENTE_DESTINATARIO ) REFERENCES SA_CLIENTE ( ID_CLIENTE ) ;

ALTER TABLE SA_DIRECCION ADD CONSTRAINT SA_CLIENTE_FK FOREIGN KEY ( ID_CLIENTE ) REFERENCES SA_CLIENTE ( ID_CLIENTE ) ;

ALTER TABLE SA_OPERACION ADD CONSTRAINT SA_CLIENTE_REM_FK FOREIGN KEY ( ID_CLIENTE_REMITENTE ) REFERENCES SA_CLIENTE ( ID_CLIENTE ) ;

ALTER TABLE SA_PROVINCIA ADD CONSTRAINT SA_DEPARTAMENTO_FK FOREIGN KEY ( ID_DEPARTAMENTO ) REFERENCES SA_DEPARTAMENTO ( ID_DEPARTAMENTO ) ;

ALTER TABLE SA_OPERACION ADD CONSTRAINT SA_DIRECCION_DES_FK FOREIGN KEY ( ID_DIRECCION_DESTINATARIO ) REFERENCES SA_DIRECCION ( ID_DIRECCION ) ;

ALTER TABLE SA_OPERACION ADD CONSTRAINT SA_DIRECCION_REM_FK FOREIGN KEY ( ID_DIRECCION_REMITENTE ) REFERENCES SA_DIRECCION ( ID_DIRECCION ) ;

ALTER TABLE SA_DIRECCION ADD CONSTRAINT SA_DISTRITO_FK FOREIGN KEY ( ID_DISTRITO ) REFERENCES SA_DISTRITO ( ID_DISTRITO ) ;

ALTER TABLE SA_DETALLE_ALERTA ADD CONSTRAINT SA_OPERACION_FK FOREIGN KEY ( ID_OPERACION ) REFERENCES SA_OPERACION ( ID_OPERACION ) ;

ALTER TABLE SA_DISTRITO ADD CONSTRAINT SA_PROVINCIA_FK FOREIGN KEY ( ID_PROVINCIA ) REFERENCES SA_PROVINCIA ( ID_PROVINCIA ) ;

ALTER TABLE SA_CLIENTE ADD CONSTRAINT SA_TIPO_CLIENTE_FK FOREIGN KEY ( ID_TIPO_CLIENTE ) REFERENCES SA_TIPO_CLIENTE ( ID_TIPO_CLIENTE ) ;
